// eslint-disable-next-line no-undef
module.exports = {
    siteName: "Strueker.dev",
    siteAuthor: "@timomrx",
    siteURL: "https://strueker.dev",
    modules: {
        blog: false,
        projects: true,
        donation: false,
    },
    payPalMail: "timo@strueker.net",
    siteKeywords:
        "Timo Strüker, Timo, Strüker, IT, IT Administrator, Developer",
    iconPath: "src/images/Strueker.dev@10x.png",
    languages: ["en", "de"],
    contactEmail: "developer@strueker.net",
    contactPhone: "+4900000000",
    address: "22309 Hamburg, Hamburg, Germany",
    mapsLink: "https://goo.gl/maps/8MSgFK6CYpmANVJd8",
    contactTwitter: "Timomrx",
    contactGitHub: "Echelon101",
    contactMastodon: "@timo@1in1.net",
    contactMastodonHref: "https://mastodon.1in1.net/@omen",
    givenName: "Timo",
    familyName: "Strüker",
    birthDate: "1999-06-28",
    gender: "Male",
    height: "188 cm",
    nationality: "Germany",
    personImage: "./content/images/timo.jpg",
    sameAs: [
        "https://mastodon.1in1.net/@timo",
        "https://github.com/Echelon101",
        "https://echelon101.net",
        "https://omendarkly.net",
        "https://strueker.net",
        "https://twitter.com/@timomrx",
    ],
};
